# Generated by Django 6.0.4 on 2026-04-27 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_team_fixture_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='teams/'),
        ),
        migrations.AddField(
            model_name='team',
            name='is_internal',
            field=models.BooleanField(default=False, help_text='Set to True for club teams that should appear on the Teams page.'),
        ),
        migrations.AddField(
            model_name='team',
            name='managers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='team',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='team',
            name='training_times',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='team',
            name='category',
            field=models.CharField(choices=[('adult', 'Adult'), ('juvenile', 'Juvenile'), ('ladies', 'Ladies')], max_length=20),
        ),
    ]
