# Generated by Django 6.0.4 on 2026-04-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_team_contact_email_team_image_team_is_internal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixturesPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Fixtures & Results', max_length=200)),
                ('hero_subtitle', models.TextField(default='Upcoming matches and latest final scores')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fixtures page content',
                'verbose_name_plural': 'Fixtures page content',
            },
        ),
        migrations.CreateModel(
            name='TeamsPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='OUR TEAMS', max_length=200)),
                ('hero_subtitle', models.TextField(default='Use this page as the club teams hub, with direct links to each section and a gallery that stays here on the main teams page')),
                ('hub_eyebrow', models.CharField(default='Teams Hub', max_length=80)),
                ('hub_title', models.CharField(default='Explore Team Sections', max_length=200)),
                ('hub_description', models.TextField(default='Each area below links to its own dedicated page. Adult Teams, Juvenile Teams, Social, and Scór now live as separate destinations, while the gallery remains here on the main Teams page.')),
                ('gallery_eyebrow', models.CharField(default='Gallery', max_length=80)),
                ('gallery_title', models.CharField(default='Gallery', max_length=200)),
                ('gallery_description', models.TextField(default='The gallery remains on the main Teams page and can continue to showcase images from across every section of the club.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Teams page content',
                'verbose_name_plural': 'Teams page content',
            },
        ),
    ]
