# Generated by Django 6.0.4 on 2026-04-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_fixturespagecontent_teamspagecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixturespagecontent',
            name='archive_cta_button_text',
            field=models.CharField(default='View Results Archive', max_length=100),
        ),
        migrations.AddField(
            model_name='fixturespagecontent',
            name='archive_cta_description',
            field=models.TextField(default='Browse all recorded match results and use the built-in filters to find a specific team or category quickly.'),
        ),
        migrations.AddField(
            model_name='fixturespagecontent',
            name='archive_cta_title',
            field=models.CharField(default='Need the full results archive?', max_length=200),
        ),
        migrations.AddField(
            model_name='fixturespagecontent',
            name='results_subtitle',
            field=models.CharField(default='Most Recent Finals First', max_length=200),
        ),
        migrations.AddField(
            model_name='fixturespagecontent',
            name='results_title',
            field=models.CharField(default='Latest Results', max_length=200),
        ),
        migrations.AddField(
            model_name='fixturespagecontent',
            name='upcoming_subtitle',
            field=models.CharField(default='Sorted By Date', max_length=200),
        ),
        migrations.AddField(
            model_name='fixturespagecontent',
            name='upcoming_title',
            field=models.CharField(default='Upcoming Fixtures', max_length=200),
        ),
        migrations.AddField(
            model_name='teamspagecontent',
            name='adult_description',
            field=models.TextField(default='Browse the adult football section, including links onward to the senior men, senior ladies, and social overview pages.'),
        ),
        migrations.AddField(
            model_name='teamspagecontent',
            name='adult_title',
            field=models.CharField(default='Adult Teams', max_length=100),
        ),
        migrations.AddField(
            model_name='teamspagecontent',
            name='juvenile_description',
            field=models.TextField(default='Open the juvenile pathway page to view the full structure of teams and the current placeholder team details layout.'),
        ),
        migrations.AddField(
            model_name='teamspagecontent',
            name='juvenile_title',
            field=models.CharField(default='Juvenile Teams', max_length=100),
        ),
        migrations.AddField(
            model_name='teamspagecontent',
            name='scor_description',
            field=models.TextField(default='Explore the dedicated Scór page for the cultural side of the club, including music, performance, storytelling, and quiz activity.'),
        ),
        migrations.AddField(
            model_name='teamspagecontent',
            name='scor_title',
            field=models.CharField(default='Scór', max_length=100),
        ),
        migrations.AddField(
            model_name='teamspagecontent',
            name='social_description',
            field=models.TextField(default='Visit the social section for direct access to G4MO, G4DL, and Furious but not Fast.'),
        ),
        migrations.AddField(
            model_name='teamspagecontent',
            name='social_title',
            field=models.CharField(default='Social', max_length=100),
        ),
    ]
