# Generated by Django 6.0.4 on 2026-04-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_juvenileteamspagecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('time', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Matches', 'Matches'), ('Club Events', 'Club Events'), ('Training', 'Training')], default='Club Events', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/')),
            ],
            options={
                'ordering': ['date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='EventsPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Club Events', max_length=200)),
                ('hero_subtitle', models.TextField(default='Fixtures, meetings, and social gatherings.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Events page content',
                'verbose_name_plural': 'Events page content',
            },
        ),
        migrations.CreateModel(
            name='ClubTeam',
            fields=[
            ],
            options={
                'verbose_name': 'Club team',
                'verbose_name_plural': 'Club teams',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.team',),
        ),
        migrations.CreateModel(
            name='OpponentClub',
            fields=[
            ],
            options={
                'verbose_name': 'Opponent club',
                'verbose_name_plural': 'Opponent clubs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.team',),
        ),
        migrations.AlterField(
            model_name='historyfigureitem',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a square image around 800x800 pixels.', null=True, upload_to='history/figures/'),
        ),
        migrations.AlterField(
            model_name='historytimelineitem',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a square image around 800x800 pixels.', null=True, upload_to='history/timeline/'),
        ),
    ]
